### ISSUE TITLE
Request to transfer 2 voices over another

### ISSUE THREAD

**Issue by Berendtol** [RussellSB/voice-conversion-gan#1]
Hi Russell,

I´m studying for months how to control Voice Style Transfer, but it´s too difficult for me.
Maybe you can help me to transfer 2 voices over another to fulfill a long youth-wish.
It´s a ZIP-file of 5 MB with the WAV-files of the voices.
You don´t have to do it for nothing, we will agree on a price.
My email is single.jingle.king@gmail.com

Kind regards,
Berend.
[VOICES.zip](https://github.com/RussellSB/voice-conversion-gan/files/6250122/VOICES.zip)

**Comment by RussellSB** [comment]
Hi Berendtol,

Thanks for your post! I'm actually still not successful in finishing my implementation, so at least right now I can't say that Im with enough experience to help out. But would be up for discussion. What model did you use?

Currently at the moment my model's suffering from mode collapse and seemingly gaussian blurred output (with a melspectrogram approach). I'm following this implementation [here](https://ebadawy.github.io/post/speech_style_transfer/). What model are you trying to follow?

Also I don't know if this is testing data but looking at it, I think you'd need much more for training for voice conversion.

Kind regards,
Russell

**Comment by Berendtol** [comment]
Hi Russell, The program that would certainly help me further is ´Voice
Style Transfer´ on GitHub and the model I tried so far was Google Colab.
Earlier I also achieved results with this when I used 'Voice Cloning', but
that was not what I was looking for.

The great thing about Google Colab is that the model only needs 10 seconds
of 'target voice' to achieve a nice result to my satisfaction.
Of course I also have longer lengths.

For instance, the example on this YouTube video is exactly what I´m looking
for to fulfill a piece of youth-nostalgia.

https://youtu.be/3BN577LK62Y

Do you know someone who has experience with this and would like to do this
for me?
It's been a big wish of mine for so long.
Thanks in advance and best regards,
Berend Tol.

Op do 15 apr. 2021 om 11:49 schreef Russell Sammut-Bonnici <
***@***.***>:

**Comment by Berendtol** [comment]
Hi Russell,

Excuse me, I didn´t realise I didn´t reply on this topic, I did by email.
I tried the model MelGAN-VC but I couldn´t figure it out
Often I hear there is a long length of audio required to train a model, but at Google Colab 10 seconds of audio is enough to clone a voice in acceptable quality.
I share a link from Wetransfer with the audiofiles, maybe you can see what can be done.
If there´s a chance you can work with, you don´t have to do it for free.
Thanks in advance.
The download-link: https://we.tl/t-nERyx7fAv4

Kind regards,
Berend.

**Comment by RussellSB** [comment]
Hi Berendtol,

Apologies! But I'm still working on improving my implementation. 

Just to politely correct you on that Google Colab is not a model, but a platform for Jupyter Notebooks. It's common for researchers to use it for training especially for portable access to sufficient GPU resources. I've heard of such models where they impressively only need 10 seconds of audio for transfer, I think they transcribe audio to text then generate audio from it if I'm not mistaken. It makes sense that the quality isn't as great as they neglect features such as intonation or rhythm.

SpeechSplit is another great model for voice conversion where they really focus on the different features posed by speech audio (https://github.com/auspicious3000/SpeechSplit)

I really appreciate your eagerness on this topic, but I'm still working on finishing my research work.  Nonetheless, I hope we can keep in touch.

Kind regards,
Russell

**Comment by Berendtol** [comment]
Hi Russell,

It´s okay, My knowledge is just not that far advanced. I´ve heard about SpeechSplit before. I just watched the YouTube film and this looks and especially sounds wonderful! 
Yes, somehow since 1993 I dreamed this should be possible some day and I feel it´s just a few steps to reality.
Of course, we keep in touch. If one of us have some questions we can possibly help each other.

Kind regards en thanks very much!
Berend.

**Comment by Berendtol** [comment]
Hi Russell,

I am very interested in this and I have also delved into it, but I couldn´t control the basics.
If it isn't too much trouble and you have some time, would you like to make a tutorial video about how to run SpeechSplit step by step?
You would do me a great pleasure.
Thanks a lot in advance!

Kind regards,
Berend.
