### ISSUE TITLE
Is this correct? Griffin Lim output almost unintelligible

### ISSUE THREAD

**Issue by SlistInc** [RussellSB/voice-conversion-gan#7]
This is a great project, congrats!

I have been trying to get it to run and so far so good, I get to the "Infer with VAE-GAN and Griffin Lim audio reconstruction" step. Using the Flickr dataset applied to the speakers 4 and 7.

My output is quite a low quality spectrogram and almost unintelligible Griffin Lim reconstruction. I was wondering whether I should change some of the training parameters to increase resolution, whether I am doing something wrong or whether this is expected and WaveNet will fix this?

I have a feeling I am doing something wrong. There is a clear correlation between input and output plots but the resolution of the output just seems to smalle. If you can point me into the right direction I would be extremely grateful.

Attached the Mel Spectrogram after step 1.4. It seems quite wrong.

![image](https://user-images.githubusercontent.com/26799535/146798962-d978ff06-424f-48da-adfe-5264d1b17c6d.png)

**Comment by RussellSB** [comment]
Have you made any edits to the `models.py` or `train.py` files? Most likely it could be something wrong with how the cyclic reconstruction is functioning. At least, I had a lot of blurring issues when I set the cyclic loss up wrongly in a few of my initial attempts.

**Comment by SlistInc** [comment]
I did not edit them other than maybe different paths in train.py (for my convenience). But it suffices to me to know that:

- The current result is not correct and I should not carry on with getting WaveNet to run yet
- You gave me a good lead where the issue might be

I will investigate. I close the issue as I suspect it lies on my side. I will put in an update in case I found a reason / solution that may help others.

**Comment by RussellSB** [comment]
Ok! Make sure you're also referencing the right model for the transfer. Keep in mind which is which for the target and source. I hope you figure out what it is - and feel free to document the solution here once you do.

**Comment by SlistInc** [comment]
Interesting... do you see anything wrong with this sequence of commands? I am running a fresh download from the repository, not doing any changes to anything in the code.

- cd data_prep/
- python flickr.py --dataroot ../InputData/ #This is the correct path to my input data
- cd ../voice_conversion/src/
- python preprocess.py --dataset ../data/data_flickr
- python train.py --model_name plaintests --dataset ../data/data_flickr --n_spkrs 2
- python inference.py --model_name plaintests --epoch 99 --trg_id 2 --src_id 1 --wavdir ../data/data_flickr/spkr_1

Either I am doing something massively wrong (very likely) or I am running into completely different issues (my hardware/setup?) that do not depend on the code. I get no errors if running this sequence, yet the first spectrogram for the first file (when running the inferrence) is this:

![image](https://user-images.githubusercontent.com/26799535/146973013-a342dd41-2e96-4a4e-a186-3588136127cd.png)

**Comment by SlistInc** [comment]
I think I may have found the issue. The following indentation in the current train.py seems fishy?

Sorry if there are better ways to report this but my experience of git is limited
<img width="828" alt="image" src="https://user-images.githubusercontent.com/26799535/147498317-987bff18-7673-4228-8435-f244709f52d1.png">

I am running the training right now, I will report back if that fixes it.

**Comment by SlistInc** [comment]
That was it. I am closing the issue and confirm that with the correct indentation (the _for i, batch in progress:_ loop needs to go into the _for epoch_ loop) I get a valid mel-spectrogram. Please be aware that there is currently a wrong indentation in the train.py file (see comment above). I am not able to fix it myself so I hope any dev can do it. Anyone running into similar issues may hopefully benefit from this finding until the code in the repository is fixed.
