### ISSUE TITLE
Two small issues in the script for training the WaveNet vocoder (run.sh)

### ISSUE THREAD

**Issue by rohitgupta3** [RussellSB/voice-conversion-gan#8]
Hi, two fairly minor questions.

1) Within the WaveNet vocoder training section, for the preprocessing step (step 2.2), it gives an example
`spk="[name]_[id]" ./run.sh --stage 1 --stop-stage 1`

Do I need to also pass hparams (à la step 2.3)? I seem to get an unbound variable if not, and I assume this is the reason.

2) The first time I run the training for the WaveNet vocoder, it appears that I get a FileNotFoundError along the lines of:
`FileNotFoundError: [Errno 2] No such file or directory: 'exp/flickr_1_train_no_dev_flickr/checkpoint_latest.pth'`

Is this because wavenet_vocoder/egs/gaussian/run.sh passes the `--checkpoint=${expdir}/checkpoint_latest.pth` argument to train.py even though (if this is a fresh model run) there wouldn't be any latest checkpoint saved? If I edit out that arg from that line, the training at least starts.

**Comment by RussellSB** [comment]
The parameter inside `run.sh` is passed how you describe it. 

The tutorial assumes you follow it using pre-trained models (which is not compulsory of course, just as a showcase). 
It refers to checkpoint latest as that is the name of the pretrained model weights file I uploaded.

It sounds correct that removing line 78 is the way to go for training things yourself. I'll update the readme with clarifications

**Comment by jodo2** [comment]
Hi, can you please advise on how to train the Wavenet vocoder? I'm struggling with step 2.2.
In step 2.1, I used `--tag test`, which created data/test_1/ and data/test_2/ for the two speakers, containing their respective data, so in step 2.2 I run:
`spk="test_1"  ./run.sh --stage 1 --stop-stage 1`  
And this results in:
`./run.sh: line 38: hparams: unbound variable`

I have then tried to run 
`spk="test_1" hparams=conf/urmp.json ./run.sh --stage 1 --stop-stage 1`
But this results in 
```
stage 1: Feature Generation
./run.sh: line 55: python: command not found
```
The path to VOC_DIR seems correct, as running only `python $VOC_DIR/preprocess.py` is possible, but I'm struggling with understanding the rest. And the same issue will arise when running stage 2 later.
